/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import BD.ConexionBD;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DatasetUtilities;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author proxc
 */
public class frmInformes extends javax.swing.JFrame implements IFormularioReceptor {

    static Calendar cal;

    DefaultTableModel modelo = new DefaultTableModel();
    ConexionBD con = new ConexionBD();
    static IFormularioReceptor _formularioInstanciador;
    String usuario = "profesor";
    String grupo = "";
    boolean modificar = false;
    private String codigoEstudiante;
    ImageIcon iconoOk = new ImageIcon("src/Presentacion/imagenes/icons8-marca-de-verificación-14.png");
    ImageIcon iconoIndefinido = new ImageIcon("src/Presentacion/imagenes/icons8-signo-de-interrogación-14.png");
    ImageIcon iconoFail = new ImageIcon("src/Presentacion/imagenes/icons8-multiplicar-14.png");
    private String consultaFecha;

    /**
     * Creates new form Home16
     */
    public frmInformes(IFormularioReceptor formularioInstanciador) {
        setIconImage(new ImageIcon(getClass().getResource("imagenes/logoupc.png")).getImage());
        _formularioInstanciador = formularioInstanciador;
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTabla = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        fileChooser = new javax.swing.JFileChooser();
        panelContenedor = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnl_table = new javax.swing.JPanel();
        pnl_chart = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnestudiante = new MaterialSwing.MaterialButtomPanel();
        jLabel15 = new javax.swing.JLabel();
        btncorte1 = new MaterialSwing.MaterialButtomPanel();
        jLabel14 = new javax.swing.JLabel();
        btndia = new MaterialSwing.MaterialButtomPanel();
        jLabel12 = new javax.swing.JLabel();
        materialButtomPanel3 = new MaterialSwing.MaterialButtomPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bntmes = new MaterialSwing.MaterialButtomPanel();
        jLabel16 = new javax.swing.JLabel();
        btnsemestre = new MaterialSwing.MaterialButtomPanel();
        jLabel21 = new javax.swing.JLabel();
        btncorte2 = new MaterialSwing.MaterialButtomPanel();
        jLabel24 = new javax.swing.JLabel();
        btncorte3 = new MaterialSwing.MaterialButtomPanel();
        jLabel23 = new javax.swing.JLabel();

        menuTabla.setBorder(null);
        menuTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTabla.setEnabled(false);
        menuTabla.setLabel("Menu de Opciones");

        jMenuItem3.setBackground(new java.awt.Color(75, 146, 45));
        jMenuItem3.setForeground(new java.awt.Color(75, 146, 45));
        jMenuItem3.setText("Opciones ");
        jMenuItem3.setEnabled(false);
        menuTabla.add(jMenuItem3);
        menuTabla.add(jSeparator1);

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuTabla.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuTabla.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        panelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowRightShadow(false);
        panelTitulo.setBorder(dropShadowBorder1);
        panelTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelTituloMouseDragged(evt);
            }
        });
        panelTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelTituloMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(112, 182, 32));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Informes ");
        jLabel18.setToolTipText("");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ingenieria del sofware");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/logoupcmediano.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel7))
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 517, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnl_table.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        pnl_table.setBorder(dropShadowBorder2);

        pnl_chart.setBackground(new java.awt.Color(255, 255, 255));
        pnl_chart.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_chart.setLayout(new javax.swing.BoxLayout(pnl_chart, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        jScrollPane2.setOpaque(false);

        tablaEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tablaEstudiantes.setForeground(new java.awt.Color(51, 51, 51));
        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "codigo", "nombre", "apellido", "asistencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEstudiantes.setGridColor(new java.awt.Color(255, 255, 255));
        tablaEstudiantes.setRowHeight(20);
        tablaEstudiantes.setSelectionBackground(new java.awt.Color(112, 182, 32));
        tablaEstudiantes.setShowHorizontalLines(false);
        tablaEstudiantes.setShowVerticalLines(false);
        tablaEstudiantes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaEstudiantes);
        if (tablaEstudiantes.getColumnModel().getColumnCount() > 0) {
            tablaEstudiantes.getColumnModel().getColumn(1).setResizable(false);
            tablaEstudiantes.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(112, 182, 32));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 146, 45));
        jLabel2.setText("TITULO DE TABLA");

        javax.swing.GroupLayout pnl_tableLayout = new javax.swing.GroupLayout(pnl_table);
        pnl_table.setLayout(pnl_tableLayout);
        pnl_tableLayout.setHorizontalGroup(
            pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnl_tableLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_chart, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        pnl_tableLayout.setVerticalGroup(
            pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tableLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_tableLayout.createSequentialGroup()
                        .addComponent(pnl_chart, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShadowSize(8);
        jPanel1.setBorder(dropShadowBorder3);

        jPanel3.setBackground(new java.awt.Color(75, 146, 45));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Control de acceso");
        jLabel19.setToolTipText("");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnestudiante.setBackground(new java.awt.Color(112, 182, 32));
        btnestudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnestudianteMouseClicked(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-estudiantes-24.png"))); // NOI18N
        jLabel15.setText("Asistencia de estudiante");

        javax.swing.GroupLayout btnestudianteLayout = new javax.swing.GroupLayout(btnestudiante);
        btnestudiante.setLayout(btnestudianteLayout);
        btnestudianteLayout.setHorizontalGroup(
            btnestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnestudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnestudianteLayout.setVerticalGroup(
            btnestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnestudianteLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        btncorte1.setBackground(new java.awt.Color(112, 182, 32));
        btncorte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncorte1MouseClicked(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-formación-24.png"))); // NOI18N
        jLabel14.setText("Asistencia primer corte");

        javax.swing.GroupLayout btncorte1Layout = new javax.swing.GroupLayout(btncorte1);
        btncorte1.setLayout(btncorte1Layout);
        btncorte1Layout.setHorizontalGroup(
            btncorte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncorte1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btncorte1Layout.setVerticalGroup(
            btncorte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncorte1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        btndia.setBackground(new java.awt.Color(112, 182, 32));
        btndia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndiaMouseClicked(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-hoy-24.png"))); // NOI18N
        jLabel12.setText("Asistencia por dìa");

        javax.swing.GroupLayout btndiaLayout = new javax.swing.GroupLayout(btndia);
        btndia.setLayout(btndiaLayout);
        btndiaLayout.setHorizontalGroup(
            btndiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btndiaLayout.setVerticalGroup(
            btndiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        materialButtomPanel3.setBackground(new java.awt.Color(112, 182, 32));
        materialButtomPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialButtomPanel3MouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-long-arrow-left-24.png"))); // NOI18N
        jLabel10.setText("Regresar");

        javax.swing.GroupLayout materialButtomPanel3Layout = new javax.swing.GroupLayout(materialButtomPanel3);
        materialButtomPanel3.setLayout(materialButtomPanel3Layout);
        materialButtomPanel3Layout.setHorizontalGroup(
            materialButtomPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialButtomPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        materialButtomPanel3Layout.setVerticalGroup(
            materialButtomPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialButtomPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icnoPrincipal.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Consultas");
        jLabel20.setToolTipText("");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bntmes.setBackground(new java.awt.Color(112, 182, 32));
        bntmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntmesMouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-fecha-desde-24.png"))); // NOI18N
        jLabel16.setText("Asistencia por mes");

        javax.swing.GroupLayout bntmesLayout = new javax.swing.GroupLayout(bntmes);
        bntmes.setLayout(bntmesLayout);
        bntmesLayout.setHorizontalGroup(
            bntmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntmesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bntmesLayout.setVerticalGroup(
            bntmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bntmesLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnsemestre.setBackground(new java.awt.Color(112, 182, 32));
        btnsemestre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsemestreMouseClicked(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-fecha-hasta-24.png"))); // NOI18N
        jLabel21.setText("Asistencia por semestre");

        javax.swing.GroupLayout btnsemestreLayout = new javax.swing.GroupLayout(btnsemestre);
        btnsemestre.setLayout(btnsemestreLayout);
        btnsemestreLayout.setHorizontalGroup(
            btnsemestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnsemestreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnsemestreLayout.setVerticalGroup(
            btnsemestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnsemestreLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        btncorte2.setBackground(new java.awt.Color(112, 182, 32));
        btncorte2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncorte2MouseClicked(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-formación-24.png"))); // NOI18N
        jLabel24.setText("Asistencia segundo corte");

        javax.swing.GroupLayout btncorte2Layout = new javax.swing.GroupLayout(btncorte2);
        btncorte2.setLayout(btncorte2Layout);
        btncorte2Layout.setHorizontalGroup(
            btncorte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncorte2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btncorte2Layout.setVerticalGroup(
            btncorte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        btncorte3.setBackground(new java.awt.Color(112, 182, 32));
        btncorte3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncorte3MouseClicked(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/imagenes/icons8-formación-24.png"))); // NOI18N
        jLabel23.setText("Asistencia tercer corte");

        javax.swing.GroupLayout btncorte3Layout = new javax.swing.GroupLayout(btncorte3);
        btncorte3.setLayout(btncorte3Layout);
        btncorte3Layout.setHorizontalGroup(
            btncorte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncorte3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btncorte3Layout.setVerticalGroup(
            btncorte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncorte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(materialButtomPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntmes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsemestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncorte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncorte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel20)
                .addGap(1, 1, 1)
                .addComponent(btnestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncorte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btncorte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncorte3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(materialButtomPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pnl_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTituloMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_panelTituloMousePressed

    private void panelTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTituloMouseDragged
        // TODO add your handling code here:


    }//GEN-LAST:event_panelTituloMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        RenderChart();
        CrearTabla();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "has echo clic en modificar");

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void materialButtomPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialButtomPanel3MouseClicked
        // TODO add your handling code here:
        _formularioInstanciador.setVisible(true);
        this.dispose();
        if (DPFP.Lector.isStarted()) {
            DPFP.Lector.stopCapture();
        }

    }//GEN-LAST:event_materialButtomPanel3MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        _formularioInstanciador.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btndiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndiaMouseClicked
        // TODO add your handling code here:
        consultaFecha = "dia";
        frmFechas frm = new frmFechas(this, this, true);
        frm.setVisible(true);

    }//GEN-LAST:event_btndiaMouseClicked


    private void btncorte1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncorte1MouseClicked
        // TODO add your handling code here:
        String gr = grupo.split(":")[1].trim();

        String sql = "SELECT e.codigo, e.nombre, e.apellido, ea.asistencia "
                + "from grupo as g, estudiante as e, estudiante_asistencia as ea, asistencia as a, corte as c "
                + "WHERE e.codigo=ea.codigo_estudiante and ea.codigo_asistencia = a.codigo_asistencia "
                + "and a.fecha <= c.fechaf and c.nombre=? and a.grupo_codigo=g.codigo and g.codigo=?";
        String[] param = {"corte1", gr};
        cargarTabla(sql, param);
    }//GEN-LAST:event_btncorte1MouseClicked

    private void btnestudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnestudianteMouseClicked
        // TODO add your handling code here:
        frmListadoEstudiante frm = new frmListadoEstudiante(this);
        frm.grupo = grupo;
        frm.setExtendedState(MAXIMIZED_BOTH);
        frm.setVisible(true);
        frm.modificar = true;
        frm.informes = true;


    }//GEN-LAST:event_btnestudianteMouseClicked

    private void bntmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntmesMouseClicked
         consultaFecha = "mes";
        frmFechas frm = new frmFechas(this, this, true);
        frm.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_bntmesMouseClicked

    private void btnsemestreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsemestreMouseClicked
        // TODO add your handling code here:
        String gr = grupo.split(":")[1].trim();
                String sql = "SELECT e.codigo, e.nombre, e.apellido ,ea.asistencia "
                        + "from estudiante as e,estudiante_asistencia as ea, grupo as g "
                        + "WHERE  e.codigo = ea.codigo_estudiante and e.grupo_codigo = g.codigo and g.codigo =?";
                String[] param = new String[]{gr};
                cargarTabla(sql, param);
               
    }//GEN-LAST:event_btnsemestreMouseClicked

    private void btncorte3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncorte3MouseClicked
        // TODO add your handling code here:

        String gr = grupo.split(":")[1].trim();

        String sql = "SELECT e.codigo, e.nombre, e.apellido, ea.asistencia "
                + "from grupo as g, estudiante as e, estudiante_asistencia as ea, asistencia as a, corte as c "
                + "WHERE e.codigo=ea.codigo_estudiante and ea.codigo_asistencia = a.codigo_asistencia "
                + "and a.fecha <= c.fechaf and c.nombre=? and a.grupo_codigo=g.codigo and g.codigo=?";
        String[] param = {"corte3", gr};
        cargarTabla(sql, param);

    }//GEN-LAST:event_btncorte3MouseClicked

    private void btncorte2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncorte2MouseClicked
        // TODO add your handling code here:

        String gr = grupo.split(":")[1].trim();

        String sql = "SELECT e.codigo, e.nombre, e.apellido, ea.asistencia "
                + "from grupo as g, estudiante as e, estudiante_asistencia as ea, asistencia as a, corte as c "
                + "WHERE e.codigo=ea.codigo_estudiante and ea.codigo_asistencia = a.codigo_asistencia "
                + "and a.fecha <= c.fechaf and c.nombre=? and a.grupo_codigo=g.codigo and g.codigo=?";
        String[] param = {"corte2", gr};
        cargarTabla(sql, param);
    }//GEN-LAST:event_btncorte2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInformes(_formularioInstanciador).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MaterialSwing.MaterialButtomPanel bntmes;
    private MaterialSwing.MaterialButtomPanel btncorte1;
    private MaterialSwing.MaterialButtomPanel btncorte2;
    private MaterialSwing.MaterialButtomPanel btncorte3;
    private MaterialSwing.MaterialButtomPanel btndia;
    private MaterialSwing.MaterialButtomPanel btnestudiante;
    private MaterialSwing.MaterialButtomPanel btnsemestre;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private MaterialSwing.MaterialButtomPanel materialButtomPanel3;
    private javax.swing.JPopupMenu menuTabla;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel pnl_chart;
    private javax.swing.JPanel pnl_table;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables

    public CategoryDataset createDataset() {
        final double[][] data = new double[][]{
            {1.0, 4.0, 3.0, 5.0, 5.0, 7.0, 7.0, 8.0},
            {5.0, 7.0, 6.0, 8.0, 4.0, 4.0, 2.0, 1.0},
            {4.0, 3.0, 2.0, 3.0, 6.0, 3.0, 4.0, 3.0}
        };

        final CategoryDataset dataset = DatasetUtilities.createCategoryDataset(
                "", "", data
        );
        return dataset;
    }

    private XYDataset createDataset2() {
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Object 1");
        XYSeries series2 = new XYSeries("Object 2");
        XYSeries series3 = new XYSeries("Object 3");

        series1.add(1.0, 2.0);
        series1.add(2.0, 3.0);
        series1.add(3.0, 2.5);
        series1.add(3.5, 2.8);
        series1.add(4.2, 6.0);

        series2.add(2.0, 1.0);
        series2.add(2.5, 2.4);
        series2.add(3.2, 1.2);
        series2.add(3.9, 2.8);
        series2.add(4.6, 3.0);

        series3.add(1.2, 4.0);
        series3.add(2.5, 4.4);
        series3.add(3.8, 4.2);
        series3.add(4.3, 3.8);
        series3.add(4.5, 4.0);

        dataset.addSeries(series1);
        dataset.addSeries(series2);
        dataset.addSeries(series3);

        return dataset;
    }

    void RenderChart() {
        CategoryDataset ds = createDataset();

        JFreeChart chart = ChartFactory.createStackedAreaChart("", "", "", ds);
        chart.setBackgroundPaint(new Color(255, 255, 255));
        chart.setBorderVisible(false);
        chart.setBorderPaint(new Color(255, 255, 255));
        chart.getCategoryPlot().setBackgroundPaint(new Color(255, 255, 255));
        chart.getCategoryPlot().setDomainGridlinePaint(new Color(255, 255, 255));
        chart.getCategoryPlot().setDomainGridlinesVisible(false);
        chart.getCategoryPlot().setOutlinePaint(new Color(255, 255, 255));

        ChartPanel cp = new ChartPanel(chart);
        cp.setBackground(new Color(255, 255, 255));

        pnl_chart.add(cp, BorderLayout.CENTER);
        pnl_chart.validate();

    }

    @Override
    public void recibirCodigo(String texto) {
        if ("fecha".equals(texto)) {
            consultaPorFecha();
        } else {
            codigoEstudiante = texto;
            String[] param = {codigoEstudiante, grupo.split(":")[1].trim()};

            String sql = "SELECT e.codigo, e.nombre, e.apellido ,ea.asistencia "
                    + "from estudiante as e,estudiante_asistencia as ea, grupo as g "
                    + "WHERE e.codigo=? and e.codigo = ea.codigo_estudiante and e.grupo_codigo = g.codigo and g.codigo =?";
            cargarTabla(sql, param);
        }
    }

    int contarAsistencias(String gr, String codigo) {
        String sql = "SELECT COUNT(ea.asistencia) as total"
                + "from grupo as g, estudiante as e, estudiante_asistencia as ea, asistencia as a "
                + "WHERE e.codigo=ea.codigo_estudiante and ea.codigo_asistencia = a.codigo_asistencia "
                + "and a.grupo_codigo=g.codigo and g.codigo=? and e.codigo=?";
        Connection c = con.conectar();

        //Obtiene todas las huellas de la bd
        PreparedStatement buscarStmt;
        try {
            buscarStmt = c.prepareStatement(sql);
            buscarStmt.setString(1, gr);
            buscarStmt.setString(2, codigo);
            ResultSet rs = buscarStmt.executeQuery();
            if (rs.next()) {
                //Lee la plantilla de la base de datos
                return rs.getInt("total");

            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(frmListadoEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public void CrearTabla() {
        String[] titulos = new String[]{"IDENTIFICACION", "NOMBRE", "APELLIDO", "ASISTENCIA"};
        modelo.setColumnIdentifiers(titulos);

        tablaEstudiantes.setDefaultRenderer(Object.class, new IconCellRenderer());
        tablaEstudiantes.setModel(modelo);
        tablaEstudiantes.setBackground(Color.white);
        //lblGrupo.setText(grupo);
    }

    public void CrearTablaNueva() {

        String gr = grupo.split(":")[1].trim();
        int num = contarAsistencias(gr, codigoEstudiante);
        String[] titulos = new String[3 + num];
        titulos[0] = "IDENTIFICACION";
        titulos[1] = "NOMBRE";
        titulos[2] = "APELLIDO";
        for (int i = 3; i < num; i++) {
            titulos[i] = "  CLASE " + i;
        }

        //lblGrupo.setText(grupo);
        modelo.setColumnIdentifiers(titulos);
        tablaEstudiantes.setDefaultRenderer(Object.class, new IconCellRenderer());
        tablaEstudiantes.setModel(modelo);
        tablaEstudiantes.setBackground(Color.white);
    }

    public void LimpiarTabla() {
        int filas = tablaEstudiantes.getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
    }

    private void cargarTabla(String sql, String[] param) {
        LimpiarTabla();
        Connection c = con.conectar();

        //Obtiene todas las huellas de la bd
        PreparedStatement buscarStmt;
        try {
            buscarStmt = c.prepareStatement(sql);
            for (int i = 0; i < param.length; i++) {
                buscarStmt.setString(i + 1, param[i]);
            }
            ResultSet rs = buscarStmt.executeQuery();
            //objetoi que almacenara todos los usuarios 
            Object[] datos = new Object[4];
            //Si se encuentra el nombre en la base de datos

            while (rs.next()) {

                //Lee la plantilla de la base de datos
                datos[0] = rs.getString("codigo");
                datos[1] = rs.getString("nombre");
                datos[2] = rs.getString("apellido");

                if ("si".equals(rs.getString("asistencia"))) {
                    // modelo.setValueAt(fila[0] = new JLabel(iconoOk), i, 0);
                    datos[3] = new JLabel(iconoOk);
                } else if ("no".equals(rs.getString("asistencia"))) {
                    //modelo.setValueAt(fila[0] = new JLabel(iconoFail), i, 0);
                    datos[3] = new JLabel(iconoFail);
                } else {
                    //modelo.setValueAt(fila[0] = new JLabel(iconoIndefinido), i, 0);
                    datos[3] = new JLabel(iconoIndefinido);
                }

                modelo.addRow(datos);

            }

            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(frmListadoEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void consultaPorFecha() {
        String sql;
        String gr = grupo.split(":")[1].trim();
        String dia = "";
        String[] param = null;
        switch (consultaFecha) {
            case "dia":

                sql = "SELECT e.codigo, e.nombre, e.apellido ,ea.asistencia "
                        + "from estudiante as e,estudiante_asistencia as ea, grupo as g,asistencia as a "
                        + "WHERE e.codigo = ea.codigo_estudiante and e.grupo_codigo = g.codigo and g.codigo =? and a.codigo_asistencia = ea.codigo_asistencia and a.fecha = ? ";
                dia = String.valueOf(cal.get(Calendar.YEAR)) + "-" + String.valueOf(cal.get(Calendar.MONTH)+1) + "-" + String.valueOf(cal.get(Calendar.DATE));

                param = new String[]{gr, dia};
                cargarTabla(sql, param);
                break;
            case "mes":
                sql = "SELECT e.codigo, e.nombre, e.apellido ,ea.asistencia "
                        + "from estudiante as e,estudiante_asistencia as ea, grupo as g,asistencia as a "
                        + "WHERE e.codigo = ea.codigo_estudiante and e.grupo_codigo = g.codigo and g.codigo =? and a.codigo_asistencia = ea.codigo_asistencia and MONTH(a.fecha) = ? and YEAR(a.fecha) = ?";

                param = new String[]{gr, String.valueOf(cal.get(Calendar.MONTH)+1), String.valueOf(cal.get(Calendar.YEAR))};
                cargarTabla(sql, param);
                break;
            

        }

    }
}
